if(${BOARD_INGENIC_T31})
    set(BOARD "T31")
elseif(${BOARD_RPI})
    set(BOARD "V4L2")
else()
    set(BOARD "FILE")
endif()
set(BUILD_WEBRTC_SAMPLES_SAVED "${BUILD_WEBRTC_SAMPLES}")
set(BUILD_WEBRTC_SAMPLES OFF)
add_subdirectory(libraries/amazon/amazon-kinesis-video-streams-media-interface)
set(BUILD_WEBRTC_SAMPLES "${BUILD_WEBRTC_SAMPLES_SAVED}")
